# Generated by Django 2.2.26 on 2022-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='tipo')),
                ('habilidade', models.CharField(blank=True, max_length=200, null='lutar', verbose_name='habilidade')),
                ('urlimagem', models.URLField()),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
            },
        ),
    ]
