# Generated by Django 4.0.1 on 2022-01-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tipo'),
        ),
    ]
