# Generated by Django 4.0.1 on 2022-01-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='habilidade',
            field=models.CharField(blank=True, max_length=50, null='lutar', verbose_name='habilidade'),
            preserve_default='lutar',
        ),
    ]
