# Generated by Django 2.2.26 on 2022-01-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_habilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='personagem',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='habilidade',
            field=models.CharField(blank=True, max_length=200, null='lutar', verbose_name='habilidade'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
