# Generated by Django 4.0.1 on 2022-01-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_remove_pokemon_upload_pokemon_urlimagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='habilidade',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='urlimagem',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
