# Generated by Django 4.0.1 on 2022-01-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_remove_pokemon_habilidade_remove_pokemon_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='defense',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='habilidade',
            field=models.CharField(blank=True, max_length=200, null='lutar', verbose_name='habilidade'),
            preserve_default='lutar',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='urlimagem',
            field=models.CharField(max_length=300, null=True, verbose_name='urlimage'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
