# Generated by Django 4.0.1 on 2022-01-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_remove_pokemon_defense_pokemon_habilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='urlimagem',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
