# Generated by Django 4.0.1 on 2022-01-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_alter_pokemon_urlimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='urlimagem',
            field=models.URLField(),
        ),
    ]
